### ISSUE TITLE
Tests don't compile with TypeScript 1.8.7

### ISSUE THREAD

**Issue by dylan-smith** [Microsoft/vso-agent-tasks#1375]
I was having TS compilation errors when trying to run gulp test.  I discovered it was because I was using a newer version of TypeScript.

![image](https://cloud.githubusercontent.com/assets/1508559/13659534/30c544aa-e648-11e5-90eb-39f528b16004.png)

My understanding is that typescript is supposed to be pinned to 1.8.0 as per PR #1294 

However, when I ran gulp test it was still using 1.8.7.  Based on some comments from @ericsciple in PR #1293 I believe it's because tsc.exe is in my PATH.  I'm assuming it got there because of how I installed it, which was following the instructions in Contribute.md, which instruct me to install it globally (or maybe it was VS that put it there, I'm not sure):
```bash
npm install typescript -g
```

If all of the above is correct, I'd suggest updating Contribute.md with instructions for how to properly setup my dev environment.

I also submitted PR #1366 which fixes toolrunner.ts so that it compiles in the latest version of TypeScript.

**Comment by jsnmc** [comment]
I hit the same problem and reported it a few days ago.  It was marked as a duplicate.  It would be helpful to have some docs on development environment setup.

**Comment by bryanmacfarlane** [comment]
There is docs for the env setup and it's linked right off the main page

https://github.com/Microsoft/vso-agent-tasks/blob/master/docs/contribute.md 

We do document that you need typescript > 1.6.  If course we're not going to document installing typescript and all the environmental issues.  That's the typescript projects job.  We're not duplicating there docs.

**Comment by dylan-smith** [comment]
If you follow the instructions in contribute.md - which tell you to do npm install typescript -g.  Then try and do a gulp test, you get a compilation error.  The instructions in contribute.md need to be updated to help us figure out how to get a working build/compile/test of this repo.

**Comment by bryanmacfarlane** [comment]
What we could do is update contribute to tell folks to run tsc --version and ensure it resolves to > 1.6.

What we shouldn't do is document all the typescript issues like I had VS and a different version was in my path, do x, y and z

What version was resolving when you got the compile issue?

**Comment by jsnmc** [comment]
Yeah, to follow up, I followed those and the build was broken because of it: 

Install TypeScript

npm install typescript -g
**You'll need at least TypeScript 1.6.**  // Obviously you need at least 1.6, but not 1.8

**Comment by bryanmacfarlane** [comment]
OK - I updates to 1.8.7 and it's highlighting a real issue in the test mock of task-lib.  We should fix that.

I think versions 1.6 - 1.7.x didn't bark on that condition

**Comment by dylan-smith** [comment]
I'm pretty sure I had a fresh Azure Visual Studio 2015 U1 VM, I followed the instructions in Contribute.md exactly.  Then ran gulp test and it failed.  This is not a case of having a messy dev environment.  This was a fresh VM built solely for the purpose of build/test of this repo.

I've since deleted the VM, but I'm creating a fresh one right now just to double-check.  If a fresh VM + the instructions from Contribute.md results in a broken build, then IMO that is something that needs to be addressed in contribute.md.

**Comment by bryanmacfarlane** [comment]
I'm fixing it right now

**Comment by bryanmacfarlane** [comment]
Fixed:

https://github.com/Microsoft/vso-agent-tasks/commit/a256e5ebcb319f1887fc5a4862b950a99cdb478a

I updated the contributor readme as well

**Comment by bryanmacfarlane** [comment]
Please confirm and close if fixed for you

**Comment by dylan-smith** [comment]
I'll try it out this evening, but it looks like you can close this PR as you just made the same change:
#1366

**Comment by jsnmc** [comment]
Thanks!

**Comment by bryanmacfarlane** [comment]
Sorry I didn't see your PR, it got lost in the bottom of the text and I missed it.  I should have taken yours

**Comment by dylan-smith** [comment]
Thanks @bryanmacfarlane
